# Generated by Django 5.2.11 on 2026-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('km1', models.IntegerField()),
                ('km2', models.IntegerField()),
                ('km3', models.IntegerField()),
                ('km4', models.IntegerField()),
                ('km5', models.IntegerField()),
                ('km6', models.IntegerField()),
                ('km7', models.IntegerField()),
                ('km8', models.IntegerField()),
                ('km9', models.IntegerField()),
                ('km10', models.IntegerField()),
            ],
        ),
    ]
